add css
miqunore/todolist pull request #6
Opened 2021-10-29 13:38 UTC by miqunore

add css, scss and loaders
need a check

2021-11-01 13:42 UTC, amalieiev requested changes

2021-11-01 13:42 UTC, amalieiev commented on src/core/index.js
> +import './core/scss.scss';
неверный путь
файла scss.scss нет в проекте
попробуй выполнить npm run build
![image](https://user-images.githubusercontent.com/7556668/139680750-824657be-795e-4fe4-80b2-611a420ce4f7.png)

2021-11-01 13:42 UTC, amalieiev commented on webpack.config.js
> +        test: /\.s[ac]ss$/i,
Достаточно одного общего правила для css и  scss
![image](https://user-images.githubusercontent.com/7556668/139681085-b11f80b3-0d35-4992-a4b3-e1080087dfa1.png)

2021-11-02 10:45 UTC, miqunore commented on webpack.config.js
> +        test: /\.s[ac]ss$/i,
fix

2021-11-02 10:45 UTC, miqunore commented on src/core/index.js
> +import './core/scss.scss';
fix

2021-11-02 11:07 UTC, amalieiev commented on src/core/index.js
> +    //
![image](https://user-images.githubusercontent.com/7556668/139834560-83fa156e-8603-4c3c-a660-879c71546ba9.png)

2021-11-02 11:07 UTC, amalieiev commented on webpack.config.js
![image](https://user-images.githubusercontent.com/7556668/139835126-0d3d8430-4374-4642-a4a1-ff9d0bf89bc7.png)

2021-11-02 11:07 UTC, amalieiev commented on src/core/index.js
> +    //
![image](https://user-images.githubusercontent.com/7556668/139835391-77df9169-223e-4f38-a41c-f446330f9082.png)

2021-11-02 11:19 UTC, amalieiev commented on src/core/index.js
> +  parent.innerHTML + html;
parent.innerHTML = html;

2021-11-02 11:20 UTC, amalieiev commented on src/core/index.js
> +  parent.innerHTML + html;
и не забудь в index.html добавить див с id="root"

2021-11-02 11:22 UTC, miqunore commented on src/core/index.js
> +  parent.innerHTML + html;
add id="root"

2021-11-02 11:23 UTC, amalieiev commented on src/index.html
>          <h1>Список дел:</h1>
Этот контент лишний
Можно разве что поместить сюда какойто текст закрузки. Loading... например, он будет показвать пока не выполнится первый render

2021-11-02 11:24 UTC, amalieiev commented on src/index.html
>          <h1>Список дел:</h1>
<h1>Список дел:</h1>

2021-11-02 11:25 UTC, miqunore commented on src/index.html
>          <h1>Список дел:</h1>
уже убрал его

2021-11-02 11:26 UTC, amalieiev commented on src/index.html
> +    <div class="container" id="root">
старайся не добавлять классы, которые нигде не используются
![image](https://user-images.githubusercontent.com/7556668/139837936-ee4a1cc6-ac44-48f8-9324-341b0c76622b.png)

2021-11-02 11:27 UTC, amalieiev commented on src/core/index.js
> +  parent.innerHTML + html;
![image](https://user-images.githubusercontent.com/7556668/139838077-0445b1e6-4c4e-4273-909c-7f5572b20dc1.png)
тут должно быть = вместо +

2021-11-02 11:30 UTC, miqunore commented on src/index.html
> +    <div class="container" id="root">
ок, но это точно пойдет в дело

2021-11-02 11:36 UTC, miqunore commented on src/core/index.js
> +  parent.innerHTML + html;
fix

2021-11-02 11:40 UTC, amalieiev commented on src/index.html
>          <h1>Список дел:</h1>
отлично

2021-11-02 11:44 UTC, amalieiev approved these changes

2021-11-02 11:44 UTC, merged